### ISSUE TITLE
Fail on qBittorrent-cli. Aborting.

### ISSUE THREAD

**Issue by michaelwijnands-zuyd** [Jorman/Scripts#1]
I'm running a Docker container with qBittorrent 4.2.5.
When trying to run the script from Sonarr it exits with code 1.

I used the console to manually run the script from inside the Sonarr container and it says qBittorrent-CLI is missing eventhough your Readme says it is not needed anymore.
When commenting the code below the script seems to work.

```
if [[ -z $qbt_executable ]]; then
	echo -e "\n\e[0;91;1mFail on qBittorrent-cli. Aborting.\n\e[0m"
	echo "You can find it here: https://github.com/fedarovich/qbittorrent-cli"
	exit 1
fi
```

**Comment by Jorman** [comment]
Ouch, never got the notification mail about this, sorry!
You right, now this's fixed with the last commit.
Hope you've taken the last one

J
