### ISSUE TITLE
example private_tracker_list

### ISSUE THREAD

**Issue by jcrossbdn** [Jorman/Scripts#10]
Haven't been able to figure out how to use private_tracker_list

have tried (pulled from transmissions trackers list for the item) (tracker name was changed for this example though):
private_tracker_list='https://tracker.myprivatetracker.com:443'
and private_tracker_list='https://tracker.myprivatetracker.com:443/announce'

but keep getting:
Private tracker list present, checking if the torrent is private
The torrent is not private, I'll inject trackers on it

is there something obvious I'm missing here?  And how would you add multiple private trackers to this list (comma, space or newline separate)?

**Comment by jcrossbdn** [comment]
okay thanks.  I added it but it still wasn't working...

I had to make an update to line 234 and 235 to get the proper number into the torrent_found variable (I am only on 3 digit numbers in my torrents,lol)

here is the entire block from line 232
`    else # parameter is a number
      torrent_found=$(echo "$torrents_list" | \
        sed -nr '1d;/^Sum:/d;s: :0:g;s:^(....).*:\1:p' | \
        grep $(echo 0000$tor_to_search | sed -nr 's:.*([0-9]{4}$):\1:p') | sed 's/^0*//')
    fi
`

**Comment by Jorman** [comment]
Hi,
without the whole idea, it is difficult for me to better understand what do you want to achieve, this part of the code control the given torrent as number, and not the name, so, if you can please tell me some extra info I can do some "test", actually I don't use Transmission but is not a big problem I think.

Do you've also tested with "low" torrent number? I admit that I haven't tested with very large numbers so maybe some adapt are needed, but looking at the original seed I only see the 4th digits number limit.

Do you've some extra test/log to see? If all works, I can update the code
