### ISSUE TITLE
AddqBittorrentTrackers.sh curl errors

### ISSUE THREAD

**Issue by ceticdev** [Jorman/Scripts#12]
Manually trying to test this script before using it in Radarr.

Running it using the IP docker provides the container and passing the -a flag leads to a curl error.

Output shows:
```
ubuntu@main:/data$ ./trackers.sh -a
curl: (22) The requested URL returned error: 401
curl: (22) The requested URL returned error: 403
No torrents found, exiting
```

Running it with the -l flag makes me believe it's a qBittorrent issue. 
```
ubuntu@main:/data$ ./trackers.sh -l
curl: (22) The requested URL returned error: 401

Current torrents:
movie1.mkv
ubuntu@main:/data$
```

I'm using the original tracker links provided in the script and manually changed the backup trackers but nothing other than that. chown and chmod have both been run appropriately, thanks.

**Comment by Jorman** [comment]
Hi,

docker configuration are "particular" for example in my case, my NAS run over 10.0.0.100 but the docker ip is something like 172.x.x.x
In my case, I have to communicate with qBittorrent with 10.0.0.100 and not with docker ip, otherwise I can't reach docker.
But error 401 is Unauthorized, maybe you have to set qBittorrent to accept connection? Username and password is ok?

If you give me some extra information, we can try to solve this

**Comment by ceticdev** [comment]
It seems like the docker IP works as using the list flag does return the current movies. Both the credentials are correct and all connections are allowed from localhost and the docker subnet so it shouldn't be that. Not sure what other information I can give you, just confused on why I can list the torrents and still get a 401.

**Comment by Jorman** [comment]
We can try to catch the problem, but I need to see and have more information about

Can you please post here the configuration of the script and all relevant details about docker machine and the qBittorrent configuration too?
So we can plan to make some test

J

**Comment by ceticdev** [comment]
Sorry for the long wait, forgot I opened this issue. Redid my docker setup with Radarr, qBittorrent, etc and still had the same issue. The way I have my setup configured is through a docker compose stack which has a private network and all containers have their own IP assigned to it. Instead of using that private network IP I changed it to my server IP and it seems to work. I'm just a dummy ;)

**Comment by Jorman** [comment]
Hi, no problem!
Exactly, you've to use the server IP and not the docker one, like I commented here
https://github.com/Jorman/Scripts/issues/12#issuecomment-1254904651

But glad you figure it out!
