### ISSUE TITLE
AddqBittorrentTrackers, jq error on Qnap NAS

### ISSUE THREAD

**Issue by papampi** [Jorman/Scripts#16]
I'm getting this error when trying to run with -n 

```
[~] # /share/Download/AddqBittorrentTrackers.sh -n Pulp
jq: error (at <stdin>:1): jq was compiled without ONIGURUMA regex libary. match/test/sub and related functions are not available.
I didn't find a torrent with the text: 
No torrents found, exiting
```

I can use "-a"  , also "-l" shows torrents lists, but jq gives error on entware with "-n":
```
[~] # opkg list | grep jq
jq - 1.6-2 - Lightweight and flexible command-line JSON processor.
[~] # which jq
/opt/bin/jq
```

**Comment by Jorman** [comment]
I've to check but seems that your jq version is "limited" in functionality
Need further investigation

**Comment by Jorman** [comment]
I just pushed a new version, please try and let me know if solve the problem

**Comment by papampi** [comment]
Thanks a lot mate, that solved the issue and it's working now.
