### ISSUE TITLE
Step by step failure

### ISSUE THREAD

**Issue by Spaginni** [Jorman/Scripts#19]
This my first post sorry if its - messed up.

I loaded and edited the configuration file for qbitorrent. 

> 

########## CONFIGURATIONS ##########
# Host on which qBittorrent runs
qbt_host="http://localhost"
# Port -> the same port that is inside qBittorrent option -> Web UI -> Web User Interface
qbt_port="X123"
# Username to access to Web UI
qbt_username="user"
# Password to access to Web UI
qbt_password="passwd"

# If true (lowercase) the script will inject trackers inside private torrent too (not a good idea)
ignore_private=false

# Configure here your trackers list
declare -a live_trackers_list_urls=(
	"https://newtrackon.com/api/stable"
	"https://trackerslist.com/best.txt"
	"https://trackerslist.com/http.txt"
	"https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt"
	)

> 

~~~~~~~~~
I changed the qbt variables from their proper values. 
This configuration results in error: 
$ sh ./AddqBittorrentTrackers.sh 
./AddqBittorrentTrackers.sh: 17: Syntax error: "(" unexpected

~~~~~~~~~~~~~~
I removed the "(" and ")" to fix the error. And ran again. 
Resulting Error:

> 

$ sh ./AddqBittorrentTrackers.sh 
./AddqBittorrentTrackers.sh: 17: declare: not found
./AddqBittorrentTrackers.sh: 18: https://newtrackon.com/api/stable: not found
./AddqBittorrentTrackers.sh: 19: https://trackerslist.com/best.txt: not found
./AddqBittorrentTrackers.sh: 20: https://trackerslist.com/http.txt: not found
./AddqBittorrentTrackers.sh: 21: https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt: not found
./AddqBittorrentTrackers.sh: 32: [[: not found
./AddqBittorrentTrackers.sh: 39: [[: not found
./AddqBittorrentTrackers.sh: 140: Syntax error: redirection unexpected

> 

~~~~
 I havent been able to get past this.

**Comment by Spaginni** [comment]
Look at this, i realize i reported this issue in the wrong way... 
my bad.

**Comment by Jorman** [comment]
Hi,
I made some small modification but online, so maybe I messed up something, I've to check
But I also prefer to see all your side script, so remove the "unwanted" information and post your script, maybe in modification you removed some parts.
For example the part that you removed is necessary

What bash version do you have?

**Comment by Spaginni** [comment]
Thank you
[AddqBittorrentTrackers.txt](https://github.com/Jorman/Scripts/files/12717166/AddqBittorrentTrackers.txt)

**Comment by Jorman** [comment]
Hi,
ok, you have one "old" version, but this's not the problem.
I checked your file and you removed the two ()

So you can try to clone again the new one and modify only the configuration section.
Then, if you got some error, please report also your bash version and/or your system specification, maybe is not a script error, maybe is some on the system.

**Comment by Spaginni** [comment]
> Hi, ok, you have one "old" version, but this's not the problem. I checked your file and you removed the two ()
> 
> So you can try to clone again the new one and modify only the configuration section. Then, if you got some error, please report also your bash version and/or your system specification, maybe is not a script error, maybe is some on the system.

Ill start over, thank you.

The reason i removed the " ( ) " - was because it had an error. 

> 

$ sh ./AddqBittorrentTrackers.sh 
./AddqBittorrentTrackers.sh: 17: Syntax error: "(" unexpected

**Comment by Jorman** [comment]
Ok, try this, run
`bash -xv AddqBittorrentTrackers.sh &> log.log`

remove your personal data, if you want, and attach here the log file

**Comment by Spaginni** [comment]
> Ok, try this, run `bash -xv AddqBittorrentTrackers.sh &> log.log`
> 
> remove your personal data, if you want, and attach here the log file

[TrackerLog.log](https://github.com/Jorman/Scripts/files/12778284/TrackerLog.log)

**Comment by Jorman** [comment]
Ok, I see one "big" error
`curl: (22) The requested URL returned error: 401 Unauthorized`
So please change your configuration with
`qbt_host="http://localhost"` or `qbt_host="http://127.0.0.1"`

I also saw that the torrent list is generated (indeed it is an error, it shouldn't do that, but that's not what generates your error), so from this little test there don't seem to be any errors, change the configuration and try the execution again and see what happens.
Always keep in mind that running the script without arguments only generates the help file, the correct usage for hand execution is with arguments, unlike automatic execution for *Arr products

Let me know.

J

**Comment by Spaginni** [comment]
J,
Thank you for keeping up with me. 
I am honestly new to scripting and github. I am going to take a class or something to try to be better at this. It is frustrating.
i edited the localhost field, tried it with and without http:// in front. same error. 

$ sh AddqBittorrentTrackers.sh 
AddqBittorrentTrackers.sh: 17: Syntax error: "(" unexpected

Ive checked my user/pass and logged in via web browser to validate the credentials. 
I am trying to understand the actual error that is being produced, but im simply confused. 

Thank you again for your help. 

Spaginni~


[TrackerLog.log](https://github.com/Jorman/Scripts/files/12850545/TrackerLog.log)

**Comment by Jorman** [comment]
Ok, now the config seems good.
The problem is the way you run the script, why you invoke sh? Any special reason?
The script is made for bash, the declare functions is not working in sh, in fact if you look at the very first line, you can see `#!/bin/bash` so when the script already have his interpreter.
Just run `./AddqBittorrentTrackers.sh` and I think everything will be fine

Let me know

J

**Comment by Spaginni** [comment]
I was taught a while back that .sh is a script, and that it was the easiest way to run it. Personally, most of the time i run ./@#$# - it fails. So it became daily practice. 

i ran it. I see the usage argument requests. 
I apologize for being a newb at this. IT appears to be running. 
Thank you so much for the aide. Obviously this was user error. 

Spa

**Comment by Jorman** [comment]
No problem, I'm glad everything is working as it should.
Have fun with the script

J
