### ISSUE TITLE
AddqBittorrentTrackers.sh won't get torrents list

### ISSUE THREAD

**Issue by rmlrml** [Jorman/Scripts#2]
I don't understand this all well enough to know what dumb mistake I may be making.

qBittorrent 4.2.5 is installed and up and running on Debian sid.  jc and curl are installed and AddqBittorrentTrackers.sh is executable.  qBittorrent has multiple resumed/active torrents, but all I get is 

```
$ ./AddqBittorrentTrackers.sh
Getting torrents list ...

This script expects one or more parameters
AddqBittorrentTrackers.sh 		- list current torrents 
AddqBittorrentTrackers.sh $s1 $s2...	- add trackers to first torrent with part of name $s1 and $s2
AddqBittorrentTrackers.sh .		- add trackers to all torrents
Names are case insensitive 

Current torrents:
$ 
```
qBittorrent is set to Use a different port on each startup.  AddqBittorrentTrackers.sh's `########## CONFIGURATIONS ##########` section has no `username` or  `password` variables to set, I have no private trackers to list, and `host` is set to http://localhost and `port` is the port I see in the qBittorrent Execution Log next to "Embedded Tracker" right after launch.  Is that the wrong port to use?

Thanks

**Comment by Jorman** [comment]
Hi, I think you configured the port in a "wrong" way, I've to better explain how to configure it!
The port have to be configured like the example below, that port is the one you use for the remote control, under web interface config section on qBittorrent. The script for now is not ready for username/password, because you can set to skip the autentication for local user, so ...
```
########## CONFIGURATIONS ##########
# Host on which qBittorrent runs
host="http://localhost"
# Port
port="8081"
# Configure here your private trackers
private_tracker_list=''
# Configure here your trackers list
live_trackers_list_url='https://newtrackon.com/api/stable'
########## CONFIGURATIONS ##########
```

Let me know

J

**Comment by rmlrml** [comment]
Thank you.  I turned on WebUI in qBittorrent settings.  It complained that port 8080 was already being used so I changed it and set it in AddqBittorrentTrackers.sh and now it works!

**Comment by Jorman** [comment]
Thank you too to point me that the README need a better explanation about it!
I'll modify the script too in order to include username and password.

J

**Comment by Jorman** [comment]
Added username and password for qBittorrent
