### ISSUE TITLE
Trackers aren't added via Sonarr/Radarr on Transmission

### ISSUE THREAD

**Issue by cellulosa** [Jorman/Scripts#20]
hi @Jorman and thank you for the great script!

I followed the instructions and can make it work when run manually (with `-a`), but it seems the script is not being handled correctly by sonarr `4.0.0.733` and radarr `5.2.3.8303` on Transmission `4.0.4`, as no trackers are added to new torrents on grab.

Is there a way to help you debug this and see what's going on?

**Comment by cellulosa** [comment]
You're a star! Grazie, @Jorman!

**Comment by Jorman** [comment]
You are welcome,
thanks to you, as you see very few people use Transmission, the last commit was a year ago and nobody ever reported this problem to me.
