### ISSUE TITLE
Qnap bad substitution

### ISSUE THREAD

**Issue by papampi** [Jorman/Scripts#26]
https://github.com/Jorman/Scripts/blob/54b172406cf4699c726f1b2e0ad3b47a32aa8d25/AddqBittorrentTrackers.sh#L48

Qnap gives error on this argument:

```
bash  AddqBittorrentTrackers.sh -h
AddqBittorrentTrackers.sh: line 49: ${qbt_host,,}: bad substitution

```
May be change it to this simpler one

`if [[ $qbt_host == "https://"* ]]; then
`

**Comment by Jorman** [comment]
Hi, not tried with QNAP, I have one but modified with Debian, so I can't test.
Is that working for your side this mod?

**Comment by papampi** [comment]
Yes the modified works without error,
These two simple ones both works without error:

`if echo "$qbt_host" | grep -q "https" ; then
` 
`if [[ $qbt_host == "https://"* ]]; then
`

Whichever you like more.

**Comment by Jorman** [comment]
Thank you for point me out this.
I'll make the new pull
