### ISSUE TITLE
AddqBittorrentTracker.sh on Synology

### ISSUE THREAD

**Issue by munkinasack** [Jorman/Scripts#27]
Regarding AddqBittorrentTrackers.sh [at this line](https://github.com/Jorman/Scripts/blob/6195d05cd716c57b8914a6c6cc058f49bf7614a3/AddqBittorrentTrackers.sh#L134) 
Synology DSM 7 doesn’t have the “rev” command. So I replaced:
` | tail -n +4 | tr '\n' '|' | rev | cut -c2- | rev)`

With:

`| tail -n +4 | tr '\n' '|' | grep -o . | tac | tr -d '\n' | cut -c2- | grep -o . | tac | tr -d '\n')`

This seems to work for me. I am not skilled in programming. Just used my Google Foo to find this option.

**Comment by Jorman** [comment]
Ciao @munkinasack 
I've to better check compatibility for this, but I think is possible to use it, let me check in the next few days
At this point I don't remember why I used rev, maybe one implementation from another use, better check before

Thanks to point me out!
