### ISSUE TITLE
Radarr: AddqBittorrentTrackers.sh	curl: (22) The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by omygolly** [Jorman/Scripts#3]
Hi and cheers for the scripts, they seem to work great from within the consol of my Radarr docker instance. Updating all the trackers as indended. However, Radarr seem to have some sort of problem handling the script and fills the log with 404s. Anyone else stumbled upon the same problem?

**Comment by omygolly** [comment]
<img width="794" alt="radarr" src="https://user-images.githubusercontent.com/18568257/96371051-3cd42200-1160-11eb-82be-3d6fe5556510.png">

Nothing special here and the test returns success.

**Comment by Jorman** [comment]
I'm over radarr v3 and no problem here, just tried
Are you using the last commit of the script?
Can you provide a log? With a log I can see what happen and why don't works

J

**Comment by omygolly** [comment]
`20-10-19 08:22:31.0|Debug|CustomScript|Executing external script: /config/scripts/AddqBittorrentTrackers.sh
20-10-19 08:22:31.0|Debug|AddqBittorrentTrackers.sh|Starting /config/scripts/AddqBittorrentTrackers.sh 
20-10-19 08:22:31.1|Debug|AddqBittorrentTrackers.sh|Sonarr varialbe found -> SABnzbd_nzo_izefonl9
20-10-19 08:22:31.1|Debug|AddqBittorrentTrackers.sh|I'll wait 10 to be sure ...
20-10-19 08:22:31.1|Debug|AddqBittorrentTrackers.sh|10[0K
20-10-19 08:22:32.1|Debug|AddqBittorrentTrackers.sh|9[0K
20-10-19 08:22:33.1|Debug|AddqBittorrentTrackers.sh|8[0K
20-10-19 08:22:33.9|Debug|Api|[GET] /api/health: 200.OK (1 ms)
20-10-19 08:22:33.9|Debug|Api|[GET] /api/health: 200.OK (1 ms)
20-10-19 08:22:34.1|Debug|Api|[GET] /api/diskspace: 200.OK (146 ms)
20-10-19 08:22:34.1|Debug|AddqBittorrentTrackers.sh|7[0K
20-10-19 08:22:34.2|Debug|Api|[GET] /api/diskspace: 200.OK (143 ms)
20-10-19 08:22:35.1|Debug|AddqBittorrentTrackers.sh|6[0K
20-10-19 08:22:36.0|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (11 ms)
20-10-19 08:22:36.0|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (6 ms)
20-10-19 08:22:36.1|Debug|AddqBittorrentTrackers.sh|5[0K
20-10-19 08:22:37.1|Debug|AddqBittorrentTrackers.sh|4[0K
20-10-19 08:22:38.1|Debug|AddqBittorrentTrackers.sh|3[0K
20-10-19 08:22:39.1|Debug|AddqBittorrentTrackers.sh|2[0K
20-10-19 08:22:40.1|Debug|AddqBittorrentTrackers.sh|1[0K
20-10-19 08:22:41.1|Debug|AddqBittorrentTrackers.sh|Getting cookie ...
20-10-19 08:22:41.3|Debug|AddqBittorrentTrackers.sh|done
20-10-19 08:22:41.3|Debug|AddqBittorrentTrackers.sh|Getting torrents list ...
20-10-19 08:22:41.3|Debug|AddqBittorrentTrackers.sh|done
20-10-19 08:22:41.3|Debug|AddqBittorrentTrackers.sh|Auto torrent mode, Sonarr download
20-10-19 08:22:41.3|Debug|AddqBittorrentTrackers.sh|hash -> sabnzbd_nzo_izefonl9
20-10-19 08:22:41.3|Debug|AddqBittorrentTrackers.sh|[0m[33mPrivate tracker list present, checking if the torrent is private[0m
20-10-19 08:22:41.4|Debug|AddqBittorrentTrackers.sh|Torrent is not private I'll inject trackers
20-10-19 08:22:41.4|Debug|AddqBittorrentTrackers.sh|Tracker file exist, I'll check if I need to upgrade it
20-10-19 08:22:41.4|Debug|AddqBittorrentTrackers.sh|File /home/nobody/TorrentTrackersList is not older than 1 days and I don't need to upgrade it
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m1/59 - Adding tracker udp://tracker.coppersurfer.tk:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m2/59 - Adding tracker http://tracker.internetwarriors.net:1337/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m3/59 - Adding tracker udp://tracker.internetwarriors.net:1337/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m4/59 - Adding tracker udp://tracker.opentrackr.org:1337/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m5/59 - Adding tracker udp://9.rarbg.to:2710/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m6/59 - Adding tracker udp://exodus.desync.com:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m7/59 - Adding tracker udp://explodie.org:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m8/59 - Adding tracker http://explodie.org:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m9/59 - Adding tracker udp://public.popcorn-tracker.org:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m10/59 - Adding tracker udp://tracker.vanitycore.co:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m11/59 - Adding tracker http://tracker.vanitycore.co:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.6|Debug|AddqBittorrentTrackers.sh|[0;36;1m12/59 - Adding tracker udp://tracker1.itzmx.com:8080/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.6|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m13/59 - Adding tracker http://tracker1.itzmx.com:8080/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m14/59 - Adding tracker udp://ipv4.tracker.harry.lu:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m15/59 - Adding tracker udp://tracker.torrent.eu.org:451/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m16/59 - Adding tracker udp://tracker.tiny-vps.com:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m17/59 - Adding tracker udp://tracker.port443.xyz:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m18/59 - Adding tracker udp://open.stealth.si:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m19/59 - Adding tracker udp://open.demonii.si:1337/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m20/59 - Adding tracker udp://denis.stalker.upeer.me:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m21/59 - Adding tracker udp://bt.xxx-tracker.com:2710/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m22/59 - Adding tracker http://tracker.port443.xyz:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.7|Debug|AddqBittorrentTrackers.sh|[0;36;1m23/59 - Adding tracker udp://tracker2.itzmx.com:6961/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.7|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m24/59 - Adding tracker udp://retracker.lanta-net.ru:2710/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m25/59 - Adding tracker http://tracker2.itzmx.com:6961/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m26/59 - Adding tracker http://tracker4.itzmx.com:2710/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m27/59 - Adding tracker http://tracker3.itzmx.com:6961/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m28/59 - Adding tracker http://tracker.city9x.com:2710/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m29/59 - Adding tracker http://torrent.nwps.ws:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m30/59 - Adding tracker http://retracker.telecom.by:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m31/59 - Adding tracker http://open.acgnxtracker.com:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m32/59 - Adding tracker wss://ltrackr.iamhansen.xyz:443/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m33/59 - Adding tracker udp://zephir.monocul.us:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m34/59 - Adding tracker udp://tracker.toss.li:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.8|Debug|AddqBittorrentTrackers.sh|[0;36;1m35/59 - Adding tracker http://opentracker.xyz:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.8|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m36/59 - Adding tracker http://open.trackerlist.xyz:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m37/59 - Adding tracker udp://tracker.swateam.org.uk:2710/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m38/59 - Adding tracker udp://tracker.kamigami.org:2710/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m39/59 - Adding tracker udp://tracker.iamhansen.xyz:2000/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m40/59 - Adding tracker udp://tracker.ds.is:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m41/59 - Adding tracker udp://pubt.in:2710/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m42/59 - Adding tracker https://tracker.fastdownload.xyz:443/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m43/59 - Adding tracker https://opentracker.xyz:443/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m44/59 - Adding tracker http://tracker.torrentyorg.pl:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m45/59 - Adding tracker http://t.nyaatracker.com:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m46/59 - Adding tracker http://open.acgtracker.com:1096/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:41.9|Debug|AddqBittorrentTrackers.sh|[0;36;1m47/59 - Adding tracker wss://tracker.openwebtorrent.com:443/announce[0;36m - [31m< Failed > 
20-10-19 08:22:41.9|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m48/59 - Adding tracker wss://tracker.fastcast.nz:443/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m49/59 - Adding tracker wss://tracker.btorrent.xyz:443/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m50/59 - Adding tracker udp://tracker.justseed.it:1337/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m51/59 - Adding tracker udp://thetracker.org:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m52/59 - Adding tracker udp://packages.crunchbangplusplus.org:6969/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m53/59 - Adding tracker https://1337.abcvg.info:443/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m54/59 - Adding tracker http://tracker.tfile.me:80/announce.php[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m55/59 - Adding tracker http://tracker.tfile.me:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m56/59 - Adding tracker http://tracker.tfile.co:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m57/59 - Adding tracker http://retracker.mgts.by:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.0|Debug|AddqBittorrentTrackers.sh|[0;36;1m58/59 - Adding tracker http://peersteers.org:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.0|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.1|Debug|AddqBittorrentTrackers.sh|[0;36;1m59/59 - Adding tracker http://fxtt.ru:80/announce[0;36m - [31m< Failed > 
20-10-19 08:22:42.1|Error|AddqBittorrentTrackers.sh|curl: (22) The requested URL returned error: 404 Not Found
20-10-19 08:22:42.1|Debug|AddqBittorrentTrackers.sh|Done!
20-10-19 08:22:42.1|Debug|CustomScript|Executed external script: /config/scripts/AddqBittorrentTrackers.sh - Status: 0
20-10-19 08:22:42.1|Debug|CustomScript|Script Output: `

**Comment by omygolly** [comment]
Thats obviously from Sonarr, but I have the same settings as in Radarr.. :)

**Comment by Jorman** [comment]
Hi,
have you installed curl?
I don't know what is your machine but if you use curl from your busybox can you have a "basic" curl ...

**Comment by Jorman** [comment]
Wait maybe I found the problem
`20-10-19 08:22:31.1|Debug|AddqBittorrentTrackers.sh|Sonarr varialbe found -> SABnzbd_nzo_izefonl9`
This download is not a torrent, right?
If I'm right I've to add a simple check to process only torrent download, I never put in because I don't use SABnz but can prevent this...

Let me know

**Comment by omygolly** [comment]
Yeah, might be it! I use both sabnzb and torrents and nzbhydra/jacket-combo as an indexer for both.

**Comment by omygolly** [comment]
Ill test disabling the nzb-indexing to see if the problem prevails.

**Comment by omygolly** [comment]
Not getting the same 404's when disabling nzb-indexing. Unfortuntally wget seems to be missing from my radarr docker container.. :/

`/config/scripts/AddqBittorrentTrackers.sh: line 41: wget: command not found`

**Comment by omygolly** [comment]
Should be able to swap out wget for curl right?

**Comment by Jorman** [comment]
Yep, this's the main problem that take me out from the container world! I can't decide what have to be inside without make a new container ... for me docker and Co. are not so good in all these configurations, but this's my personal opinion.
Btw, you can switch to curl, no problem at all!

So here we have more than one problem
`20-10-19 08:22:41.3|Debug|AddqBittorrentTrackers.sh|hash -> sabnzbd_nzo_izefonl9`
This indicate that radarr/sonarr run this script even when a nzb is grabbed
Then you told me that wget is not available on your container so ...
I'll switch from wget to curl when the script update the trackerlist, and I'll insert a new check to skip nzb grabs

**Comment by omygolly** [comment]
That would be awesome, thanks!

**Comment by Jorman** [comment]
Resolved with https://github.com/Jorman/Scripts/commit/82eded23fc4ec705ce5dcd4cac581605fe5714b6
