### ISSUE TITLE
AddqBittorrentTrackers.sh for Lidarr ?

### ISSUE THREAD

**Issue by wieluk** [Jorman/Scripts#4]
If I try to add it to custom scripts like in radarr/sonarr it just says "Script exited with code: 1" when I press test so I can not save it.
Any way to add it in Lidarr?

**Comment by Jorman** [comment]
I'll see if that is possible later.
Do you modify the script in order to use with lidarr, or just tried to put it on?

**Comment by wieluk** [comment]
I just used the same script as for radarr/sonarr it is your script with modified private trackers

**Comment by Jorman** [comment]
Just committed a test, please try and let me know

**Comment by wieluk** [comment]
thanks a lot for your fast help. Works for lidarr aswell now 👍

**Comment by Jorman** [comment]
You're welcome!
