### ISSUE TITLE
Help deleting 1 specific tracker via Powershell please

### ISSUE THREAD

**Issue by gggirlgeek** [Jorman/Scripts#40]
Hi,

Would someone here be willing to help me write a Powershell script to delete a tracker I accidentally put into all of my 4000 torrents.

Somehow I pasted this line (below) into my Auto-add-to-trackers setting in qBittorrent. Now I want to get rid of it without cleaning all of the other trackers.

Thanks so much if you can help!  

`
** [DHT] ** ** [PeX] ** ** [LSD] ** udp://p4p.arenabg.com:1337/announce udp://tracker.torrent.eu.org:451/announce udp://tracker.dler.org:6969/announce udp://open.stealth.si:80/announce udp://ipv4.tracker.harry.lu:80/announce https://opentracker.i2p.rocks:443/announce`

**Comment by Jorman** [comment]
Inside the qBittorrent wiki dedicated to the API
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)
You find a lot of information on how to send a request for deletion of one or more trackers

Alternatively, take a look at this project
https://github.com/fedarovich/qbittorrent-cli
It might be for you

**Comment by gggirlgeek** [comment]
OK. Actually, I found where you can delete 1 tracker for many torrents in the qBittorrent sidebar. So I'm all set. Thank you!
