### ISSUE TITLE
How can I get AddqBittorrentTrackers.sh to work with docker?

### ISSUE THREAD

**Issue by azumukupoe** [Jorman/Scripts#5]
I can run the script within Radarr/Sonarr's containers but it doesn't work as a custom script in both applications

**Comment by Jorman** [comment]
Hi, I don't use containers, so for me is not so easy do a fix, but if you can post some logs I can try to understand what block the script. My first idea is that script can't write the files that it needs to work, but I need to see some log to help.

**Comment by azumukupoe** [comment]
Sure

```
2021-3-7 02:43:15.3|Error|AddqBittorrentTrackers.sh|/downloads/AddqBittorrentTrackers.sh: line 45: /root/TorrentTrackersList: Permission denied
2021-3-7 02:43:15.3|Error|AddqBittorrentTrackers.sh|sed: can't read /root/TorrentTrackersList: Permission denied
2021-3-7 02:43:15.3|Error|AddqBittorrentTrackers.sh|cat: /root/TorrentTrackersList: Permission denied
2021-3-7 02:43:15.3|Error|AddqBittorrentTrackers.sh|grep: /root/TorrentTrackersList: Permission denied
```

**Comment by Jorman** [comment]
Okay, good first guess.
I'll try some

**Comment by Jorman** [comment]
Can you try the commit push and tell me if is working? If not please post the log files

J

**Comment by kingzleshe** [comment]
same here use docker.
I have tried new commit， no luck :(

**Comment by azumukupoe** [comment]
Same
```
2021-3-7 09:14:34.2|Error|AddqBittorrentTrackers.sh|/downloads/AddqBittorrentTrackers.sh: line 18: /root/TorrentTrackersList: Permission denied
2021-3-7 09:14:44.8|Error|AddqBittorrentTrackers.sh|/downloads/AddqBittorrentTrackers.sh: line 50: /downloads: Is a directory
2021-3-7 09:14:44.8|Error|AddqBittorrentTrackers.sh|sed: couldn't edit /downloads: not a regular file
2021-3-7 09:14:44.8|Error|AddqBittorrentTrackers.sh|cat: /downloads: Is a directory
2021-3-7 09:14:44.8|Error|AddqBittorrentTrackers.sh|grep: /downloads: Is a directory
```

**Comment by kingzleshe** [comment]
sorry I just found out my script file did not store at $HOME path
After I sort that out, It worked.

**Comment by kingzleshe** [comment]
> Same
> 
> ```
> 2021-3-7 09:14:34.2|Error|AddqBittorrentTrackers.sh|/downloads/AddqBittorrentTrackers.sh: line 18: /root/TorrentTrackersList: Permission denied
> 2021-3-7 09:14:44.8|Error|AddqBittorrentTrackers.sh|/downloads/AddqBittorrentTrackers.sh: line 50: /downloads: Is a directory
> 2021-3-7 09:14:44.8|Error|AddqBittorrentTrackers.sh|sed: couldn't edit /downloads: not a regular file
> 2021-3-7 09:14:44.8|Error|AddqBittorrentTrackers.sh|cat: /downloads: Is a directory
> 2021-3-7 09:14:44.8|Error|AddqBittorrentTrackers.sh|grep: /downloads: Is a directory
> ```

try to use an absolute path
I used "/media/download/TorrentTrackersList"  instead of  "$HOME/TorrentTrackersList"

**Comment by Jorman** [comment]
Okay, the easiest thing to do is to specify a custom path.
I added an option in the configuration -> custom_save_path
If set the file will be saved on that location, otherwise on home directory.

Let me know if this can bypass this problem

**Comment by azumukupoe** [comment]
It works! Thank you!
