### ISSUE TITLE
multiple trackers list?

### ISSUE THREAD

**Issue by somedevreally** [Jorman/Scripts#7]
hello,

how can i add multiple live_trackers_list_url?
is it possible?

thanks for the script.

**Comment by Jorman** [comment]
Hi, give a try, I added a possibility to specify more than one web source.

Let me know if it is working for you, I tried and seems to work good

J

**Comment by somedevreally** [comment]
awesome, works great.

if I run script manually I see 310 trackers, if the script runs through radarr on grab i see tracker count around 70.
maybe am testing it wrong

**Comment by Jorman** [comment]
Maybe the `custom_save_path` is not the same?
Try to remove the `TorrentTrackersList` file and try via Radarr again

**Comment by somedevreally** [comment]
after i deleted `TorrentTrackersList` now via radarr torrent file got 153 and `TorrentTrackersList` have 273

also there is a bug, last tracker of first list and first tracker of next list gets merged.
`https://trackme.theom.nz:443/announceudp://open.tracker.cl:1337/announce`
`wss://tracker.openwebtorrent.com:443/announcehttp://1337.abcvg.info:80/announce`

**Comment by Jorman** [comment]
Ok, I've to check it, can you tell me what urls are you using?

**Comment by somedevreally** [comment]
```
(
"https://newtrackon.com/api/stable"
"https://trackerslist.com/best.txt"
"https://trackerslist.com/http.txt"
"https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt"
 )
```

**Comment by Jorman** [comment]
I added a check to discard duplicates, you can try it.

In manual mode all is ok, if you notice some strange behavior please report also the Radarr log about the event.
Notice that via cli every line of the file is injected, even if tracker is already present in the client, this mean that if the file have 100 trackers and 30 are duplicated, you'll see 100 trackers injected but in reality only 70 are really present.
So I think this little implementation will work.

Let me know

**Comment by somedevreally** [comment]
i think the duplication check works.
but the concatenation still happens, (not big deal though) `https://trackme.theom.nz:443/announceudp://open.tracker.cl:1337/announce`

thanks again for the script

**Comment by Jorman** [comment]
Are you "open" the file via windows? I just check after a manual run but no concatenation happen.
Can you try to:
1. remove the `TorrentTrackersList`
2. do a manual run
3. cat the `TorrentTrackersList`
and see if there's concatenation?
After that
1. remove the `TorrentTrackersList`
2. do one automatic run via Radarr and check again the `TorrentTrackersList` for concatenation

Let's check if this give me some extra logs to check.

J

**Comment by Jorman** [comment]
Ok, I just tried, in manual mode I've 134 tracker injected and via Radarr is the same count, so no concatenation that "false" the results.

You got the same results?

**Comment by somedevreally** [comment]
![image](https://user-images.githubusercontent.com/26795436/147394406-119fb689-27a4-4298-8bad-833ceab9c13f.png)
check 133rd

**Comment by Jorman** [comment]
Yes, I see, I just noticed concatenations, lol, I'll try to find a solution

**Comment by Jorman** [comment]
Ok, sorry, but at first glance I don't saw the concatenation error on my side!
Now I think is working, without concatenation errors.

Take a look and let me know.

J

**Comment by somedevreally** [comment]
perfect!
now the count is same manually and through radarr.
concatenation errors is also fixed.

thanks

**Comment by Jorman** [comment]
It took me a few tries, but glad that's working
