### ISSUE TITLE
Add Readarr support

### ISSUE THREAD

**Issue by theremotheman** [Jorman/Scripts#8]
To validate script execution (and pass test event without exit code 1) in Readarr - line 263 in `AddqBittorrentTrackers.sh` (or 163 in `AddTransmissionTrackers.sh`) must be changed to

`if [[ $sonarr_eventtype == "Test" ]] || [[ $radarr_eventtype == "Test" ]] || [[ $lidarr_eventtype == "Test" ]] || [[ $readarr_eventtype == "Test" ]]; then` 

After that, everything work as expected.

**Comment by Jorman** [comment]
Hi, are not only those lines, otherwise nothing is injected, but in general yes, the principle is the same for the whole script
I added the Readarr support to qBittorrent and updted Transmission to Lidarr and Readarr too

J
